name: esda
channels:
  - conda-forge
dependencies:
  - python
  # required
  - geopandas
  - libpysal>=4.12
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - shapely
  # optional, testing, etc.
  - folium
  - mapclassify
  - matplotlib
  - numba
  - rtree
  # docs
  - nbsphinx
  - numpydoc
  - pandoc
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx_bootstrap_theme
  - mkdocs-jupyter
  - myst-parser
  - sphinx-immaterial
  - myst-nb
  - sphinx-copybutton
