---
name: Build Docs

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
    inputs:
      version:
        description: Manual Doc Build Reason
        default: test
        required: false

jobs:
  docs:
    name: Build and Push Docs (${{ matrix.os }}-${{ matrix.environment-file }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: 90
    strategy:
      matrix:
        os: ['ubuntu-latest']
        environment-file: [ci/313-latest.yaml]
        experimental: [false]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: ${{ matrix.environment-file }}
          micromamba-version: 'latest'

      - name: Install esda
        run: pip install .

      - name: Make Docs
        run: cd docs; make html

      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/
          keep_files: false
